# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('outcome', models.CharField(max_length=50, verbose_name='Outcome (eg. DNA methylation)')),
                ('exposure', models.CharField(max_length=50, verbose_name='Exposure (eg. the Trait)')),
                ('confounders', models.CharField(blank=True, max_length=200, verbose_name='Confounders (eg. Age, sex and smoking)')),
                ('outcome_unit', models.CharField(blank=True, max_length=50, verbose_name='Outcome Units')),
                ('exposure_unit', models.CharField(blank=True, max_length=50, verbose_name='Exposure Units')),
                ('array', models.CharField(max_length=50, verbose_name='Methylation Array')),
                ('tissue', models.CharField(max_length=50, verbose_name='Tissue')),
                ('further_details', models.CharField(blank=True, max_length=200, verbose_name='Further Details')),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'db_table': 'analysis',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('n', models.CharField(max_length=20, verbose_name='Total Number of Participants')),
                ('n_studies', models.CharField(max_length=20, verbose_name='Total Number of Cohorts')),
                ('categories', models.CharField(blank=True, max_length=200, verbose_name='Categories (eg. 200 smokers; 200 non-smokers)')),
                ('n_males', models.CharField(blank=True, max_length=20, verbose_name='Total Number of Males')),
                ('n_females', models.CharField(blank=True, max_length=20, verbose_name='Total Number of Females')),
                ('n_eur', models.CharField(blank=True, max_length=20, verbose_name='Total Number of Europeans')),
                ('n_eas', models.CharField(blank=True, max_length=20, verbose_name='Total Number of East Asians')),
                ('n_sas', models.CharField(blank=True, max_length=20, verbose_name='Total Number of South Asians')),
                ('n_afr', models.CharField(blank=True, max_length=20, verbose_name='Total Number of Africans')),
                ('n_amr', models.CharField(blank=True, max_length=20, verbose_name='Total Number of Admixed Americans (eg. Mexican)')),
                ('n_oth', models.CharField(blank=True, max_length=20, verbose_name='Total Number of Other Ancestry')),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'participants',
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpg', models.CharField(max_length=20, verbose_name='CpG')),
                ('beta', models.CharField(max_length=20, verbose_name='Beta')),
                ('se', models.CharField(max_length=20, verbose_name='SE')),
                ('p', models.CharField(max_length=20, verbose_name='P-value')),
                ('i2', models.CharField(blank=True, max_length=20, verbose_name='I2')),
                ('p_het', models.CharField(blank=True, max_length=20, verbose_name='P-value Heterogeneity')),
                ('dmr', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=20, verbose_name='Differentially Methylated Region Analysis')),
                ('study_id', models.CharField(blank=True, default='pmid_trait_analysis', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'results',
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('author', models.CharField(max_length=50, verbose_name='First Author (Surname Initials)')),
                ('consortium', models.CharField(blank=True, max_length=50, verbose_name='Consortium')),
                ('pmid', models.CharField(max_length=10, verbose_name='PubMed ID')),
                ('publication_date', models.DateField(verbose_name='Publication Date (DD/MM/YY)')),
                ('trait', models.CharField(max_length=100, verbose_name='Trait')),
                ('efo', models.CharField(max_length=50, verbose_name='EFO Term')),
                ('analysis', models.CharField(blank=True, max_length=100, verbose_name='Analysis (e.g. Discovery or Discovery and replication)')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Source (e.g. Table 1, Table S1)')),
                ('date_added', models.DateField(auto_now=True, verbose_name='Date Added')),
                ('user', models.CharField(max_length=50, verbose_name='User ID')),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'studies',
                'db_table': 'study',
            },
        ),
    ]
