# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='confounders',
        ),
        migrations.AddField(
            model_name='analysis',
            name='covariates',
            field=models.CharField(blank=True, max_length=200, verbose_name='Covariates (eg. Age, sex and smoking)'),
        ),
        migrations.AddField(
            model_name='participants',
            name='age',
            field=models.CharField(blank=True, max_length=5, verbose_name='Age (in years)'),
        ),
        migrations.AlterField(
            model_name='study',
            name='pmid',
            field=models.CharField(max_length=20, verbose_name='PubMed ID (or DOI)'),
        ),
    ]
