web:
  restart: always
  build: .
  container_name: dev.ewascataloginput
  volumes:
    - .:/code
  links:
    - db:db
  command: gunicorn ewas.wsgi:application --timeout 300 -w 2 -b :8080

nginx:
  restart: always
  build: ./nginx/
  container_name: dev.ewascataloginput_nginx
  ports:
    - "8000:8000"
  volumes:
    - .:/code
  volumes_from:
    - web
  links:
    - web:web

db:
  env_file:
    - ../../../settings.env
  image: mysql:5.7
  container_name: dev.ewascataloginput_db
  # environment:
     # - MYSQL_ROOT_PASSWORD=${INPUT_DATABASE_ROOT_PASSWORD}
     # - MYSQL_USER=${INPUT_DATABASE_USER}
     # - MYSQL_PASSWORD=${INPUT_DATABASE_PASSWORD}
     # - MYSQL_DATABASE=${INPUT_DATABASE_NAME}
